### PR TITLE
Reward history edge cases

### LINKED ISSUE #86: On blank pages add message saying "There is no ___ to display"

### PR DESCRIPTION
**Pull request by mllu777**
Added snackbar message if no redeemed rewards were found for an account as well if the page failed to load due to an end of stream exception

### CODE REVIEW

**Comment by mllu777** [comment]
I accidently included the files from my other pull request. The only changed file in this request is RewardHistoryFragment

**Comment by mllu777** [comment]
I'll make similar changes to other pages then re-request review.

**Comment by mllu777** [comment]
Now notifies the user if there are no chores/rewards found in AllRewardHistoryFragment, RedeemRewardFragment, SubmitChoreFragment, VerifyChoreFragment, RewardHistoryFragment

**Review by yixiaoliuw — APPROVED** [review]
RewardHistoryFragment looks good. Should have no conflicts hopefully or we will try to resolve.

**Review by yaretzj — APPROVED** [review]
Looks good

**Review by yasmineerita — APPROVED** [review]

**Pull request merged**
