### PR TITLE
Added tests and comments in the code

### LINKED ISSUE #51: Frontend Tests JUnit

### LINKED ISSUE #60: Add more in depth comments in code

### LINKED ISSUE #83: Add confirmation to delete feature

### PR DESCRIPTION
**Pull request by yixiaoliuw**
1. Added a few instrumented tests to test functionalities of the app. Certain functionalities like verify chore and redeem reward cannot be automated because there is no delete endpoints to invoke to delete verified chore or redeemed reward. 
2. Added comments and specifications throughout the implementations. There is currently an issue I have encountered and that is sometimes the instrumented test may become unstable and thus will fail (specifically an error "No views in hierarchy found matching"). In this case, since the testing account is manually set up to be ACCOUNT_ID="frontend_test", you would need to use the app with the testing account to manually delete all the chores and rewards.
3. Added alert dialogs to all functionalities (if need to update implementation, make sure update the instrumented tests as well).

### CODE REVIEW

**Comment by yixiaoliuw** [comment]
Updated tests so that the instrumented tests can pass deterministically (when no parallel tests are running). If there are parallel tests being running, you might need to manually change the testing account id so your tests are running for the specific testing account. This issue is due to having only a single database and state of the database might be different when multiple tests are running concurrently. (To improve this, we will need to keep improving the tests with capability of finding a particular chore or reward created among many different ones with the same information including name, points and description.)

**Comment by yixiaoliuw** [comment]
Added Dependency "Espresso Contrib" and added TestViewAction for performing actions on items of recycler views. This way, parallel testing will work properly. In addition, views will render properly when actions are performed on them.

**Comment by yixiaoliuw** [comment]
The Espresso instrumented tests may have control proceeding much faster than view being rendered. Adding delay using Thread.sleep(1) seems to have resolved the issue.

**Review by mllu777 — APPROVED** [review]
Looks good

**Review by yaretzj — APPROVED** [review]
Looks solid

**Review by yasmineerita — APPROVED** [review]
looks good

**Pull request merged**
