### PR TITLE
Ui/menu Changes

### PR DESCRIPTION
**Pull request by mllu777**
Changed the design of createChore/createReward to make it more consistent with other parts of the program. Changed RewardHistory elements to be more similar to SubmitChore elements. Added missing buttons to parent and child home pages. Fixed bug that prevented RewardHistory from reading the server response.

### CODE REVIEW

**Review by yixiaoliuw — APPROVED** [review]
Looks good.

**Review by yaretzj — APPROVED** [review]
Looks good

**Comment by yixiaoliuw** [comment]
Probably need to resolve conflicts introduced by the delete chore functionality first. The delete chore branch was just merged into master.

**Comment by mllu777** [comment]
I'll resolve the conflicts then re-request the reviews

**Comment by mllu777** [comment]
Fixed merge conflicts. I used the changes in master for the parent home screen.

**Review by yixiaoliuw — APPROVED** [review]
Looks good.

**Review by yaretzj — APPROVED** [review]
Thanks for fixing that!

**Pull request merged**
