### PR TITLE
Updates to Android repository

### LINKED ISSUE #27: Automatically sign in when new account is created
Don't require the parent/child to sign in again after signing up - users should be logged in after account is created

### LINKED ISSUE #33: Display parent code to parent right after account is created

### PR DESCRIPTION
**Pull request by yixiaoliuw**
I have updated README in Android directory to include user guideline and developer guideline. I have added documentation to many of the non-fragment activity classes. In addition, I have added an example AndroidJUnit4 Espresso instrumented test in the AndroidTest directory to test functionality of the CreateChoreFragment activity.

### CODE REVIEW

**Comment by yixiaoliuw** [comment]
Trying to resolve locally successful but Github Action failing instrumented test.

**Comment by yixiaoliuw** [comment]
Resolved failing reactive circus Android Emulator instrumented test. Failing test due to unclosed soft keyboard. In order to avoid similar failure, perform ViewActions.closeSoftKeyboard() whenever using ViewActions.withType().

**Comment by yixiaoliuw** [comment]
Removed .idea files because those are not pertaining to the project. Having those may cause errors on different machines.

**Comment by yixiaoliuw** [comment]
Instead of automatically sign in when new account is created, I implementation a mechanism for allowing the user to select whether return to ChooseAccount page or proceed to navigation page when new accounts are created. In my opinion this would provide more flexible choices and robust usage.

**Review by mllu777 — APPROVED** [review]
The mechanism for allowing the user to return to ChooseAccount page looks nice though when I tested it seemed to only work for signing up for a kid account. Signing up for parent accounts automatically sent me to ChooseAccount. If it is currently just set up for the creation of a child account, the pull request looks good.

**Comment by yixiaoliuw** [comment]
It should work for both. It only automatically goes to chooseAccountPage when signup fails. I will try to see if I can show sign up failure. The dialog doesn't work when some activity starts right after the dialog.

**Comment by yixiaoliuw** [comment]
In the previous version, the "return true" statement was misplaced outside of the if statement where it should be thus causing a bug returning false value whenever it should have returned true. Besides bug fix, I also changed automatic going to ChooseAccountType activity to be showing a sign up failure message with a button to choose account.

**Review by mllu777 — APPROVED** [review]
Looks Good

**Review by yaretzj — APPROVED** [review]
Looking good

**Pull request merged**
