### PR TITLE
Added Toast message to CreateChoreFragment and CreateRewardFragment

### LINKED ISSUE #74: Give confirmation toast on creation of new chore
On submit of a new chore, the app should display a toast message saying the chore is created for visual reinforcement

### LINKED ISSUE #82: Have confirmation messages as Toasts rather than hard text

### PR DESCRIPTION
**Pull request by mllu777**
Uses a toast message in CreateChore and CreateReward instead of the textview.

### CODE REVIEW

**Review by yixiaoliuw — APPROVED** [review]
Though the toast feels quite different from snackbar, I think it looks pretty good.

**Comment by mllu777** [comment]
A Snackbar probably would have been better but I was having trouble getting it to show above the keyboard so I used the Toast.

**Review by yasmineerita — APPROVED** [review]
This looks nice

**Review by yaretzj — APPROVED** [review]
Looks good

**Pull request merged**
